dist: trusty
language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - nightly


install:
    - pip install coveralls pytest pycodestyle pyspark nibabel

script:
    - pycodestyle imageutils.py tests/*.py
    - pytest ./

after_success:
    - coveralls
