dist: trusty
language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - nightly


install:
    - pip install coveralls pytest pytest-cov pycodestyle nibabel

script:
    - pycodestyle sam/imageutils.py tests/*.py
    - pytest --cov=sam ./

after_success:
    - coveralls
